// ╔══════════════════════════════════════════════════════════════════════╗
// ║  FitSofra — Kapsamlı Türk Mutfağı Besin Veritabanı                ║
// ║  ~800+ yemek · 20 kategori · TÜBİTAK/BeBiS referans değerleri     ║
// ║  Değerler: 100g başına veya parantez içinde belirtilen porsiyon     ║
// ╚══════════════════════════════════════════════════════════════════════╝
window.TURKISH_FOOD_DB = [

// ═══════════════════════════════════════════
// ══  HAMMADDE & TEMEL MALZEME (100g)     ══
// ═══════════════════════════════════════════
{name:"Un (buğday)",emoji:"🌾",cal:364,prot:10,carb:76,fat:1,cat:"hammadde"},
{name:"Şeker (toz)",emoji:"🧂",cal:387,prot:0,carb:100,fat:0,cat:"hammadde"},
{name:"Pudra Şekeri",emoji:"🧂",cal:389,prot:0,carb:100,fat:0,cat:"hammadde"},
{name:"Esmer Şeker",emoji:"🟤",cal:380,prot:0,carb:98,fat:0,cat:"hammadde"},
{name:"Zeytinyağı (1 yk)",emoji:"🫒",cal:119,prot:0,carb:0,fat:14,cat:"hammadde"},
{name:"Ayçiçek Yağı (1 yk)",emoji:"🌻",cal:120,prot:0,carb:0,fat:14,cat:"hammadde"},
{name:"Tereyağı (1 yk)",emoji:"🧈",cal:102,prot:0,carb:0,fat:12,cat:"hammadde"},
{name:"Mısırözü Yağı (1 yk)",emoji:"🌽",cal:120,prot:0,carb:0,fat:14,cat:"hammadde"},
{name:"Susam Yağı (1 yk)",emoji:"🥄",cal:120,prot:0,carb:0,fat:14,cat:"hammadde"},
{name:"Tuz (1 çk)",emoji:"🧂",cal:0,prot:0,carb:0,fat:0,cat:"hammadde"},
{name:"Pirinç (çiğ, 100g)",emoji:"🍚",cal:365,prot:7,carb:80,fat:1,cat:"hammadde"},
{name:"Bulgur (çiğ, 100g)",emoji:"🌾",cal:342,prot:12,carb:76,fat:1,cat:"hammadde"},
{name:"Makarna (çiğ, 100g)",emoji:"🍝",cal:371,prot:13,carb:75,fat:2,cat:"hammadde"},
{name:"Kırmızı Mercimek (çiğ)",emoji:"🟠",cal:352,prot:24,carb:60,fat:1,cat:"hammadde"},
{name:"Nohut (çiğ, 100g)",emoji:"🫘",cal:364,prot:19,carb:61,fat:6,cat:"hammadde"},
{name:"Kuru Fasulye (çiğ)",emoji:"🫘",cal:333,prot:21,carb:60,fat:1,cat:"hammadde"},
{name:"Yeşil Mercimek (çiğ)",emoji:"🫘",cal:353,prot:25,carb:60,fat:1,cat:"hammadde"},
{name:"İrmik (100g)",emoji:"🌾",cal:360,prot:13,carb:73,fat:1,cat:"hammadde"},
{name:"Mısır Unu (100g)",emoji:"🌽",cal:361,prot:7,carb:79,fat:2,cat:"hammadde"},
{name:"Nişasta (100g)",emoji:"🥄",cal:381,prot:0,carb:95,fat:0,cat:"hammadde"},
{name:"Galeta Unu (100g)",emoji:"🍞",cal:395,prot:13,carb:72,fat:6,cat:"hammadde"},
{name:"Tam Buğday Unu (100g)",emoji:"🌾",cal:340,prot:13,carb:72,fat:2,cat:"hammadde"},
{name:"Karabuğday (100g)",emoji:"🌾",cal:343,prot:13,carb:72,fat:3,cat:"hammadde"},
{name:"Yulaf (çiğ, 100g)",emoji:"🌾",cal:389,prot:17,carb:66,fat:7,cat:"hammadde"},
{name:"Kinoa (çiğ, 100g)",emoji:"🌾",cal:368,prot:14,carb:64,fat:6,cat:"hammadde"},
{name:"Domates Salçası (1 yk)",emoji:"🍅",cal:15,prot:1,carb:3,fat:0,cat:"hammadde"},
{name:"Biber Salçası (1 yk)",emoji:"🌶️",cal:14,prot:1,carb:3,fat:0,cat:"hammadde"},
{name:"Sirke (1 yk)",emoji:"🥄",cal:3,prot:0,carb:0,fat:0,cat:"hammadde"},
{name:"Pekmez (üzüm, 1 yk)",emoji:"🍇",cal:52,prot:0,carb:13,fat:0,cat:"hammadde"},
{name:"Tahin (1 yk)",emoji:"🥄",cal:89,prot:3,carb:3,fat:8,cat:"hammadde"},
{name:"Bal (1 yk)",emoji:"🍯",cal:64,prot:0,carb:17,fat:0,cat:"hammadde"},

// ═══════════════════════════════════════════
// ══  KAHVALTI                             ══
// ═══════════════════════════════════════════
{name:"Yumurta (haşlanmış)",emoji:"🥚",cal:155,prot:13,carb:1,fat:11,cat:"kahvalti"},
{name:"Yumurta (sahanda)",emoji:"🍳",cal:196,prot:14,carb:1,fat:15,cat:"kahvalti"},
{name:"Menemen",emoji:"🍳",cal:140,prot:8,carb:6,fat:10,cat:"kahvalti"},
{name:"Omlet (2 yumurta)",emoji:"🍳",cal:194,prot:13,carb:2,fat:15,cat:"kahvalti"},
{name:"Çırpılmış Yumurta",emoji:"🍳",cal:170,prot:12,carb:2,fat:13,cat:"kahvalti"},
{name:"Pastırmalı Yumurta",emoji:"🍳",cal:220,prot:18,carb:1,fat:16,cat:"kahvalti"},
{name:"Sucuklu Yumurta",emoji:"🍳",cal:250,prot:16,carb:2,fat:20,cat:"kahvalti"},
{name:"Beyaz Peynir (100g)",emoji:"🧀",cal:264,prot:17,carb:1,fat:21,cat:"kahvalti"},
{name:"Kaşar Peynir (100g)",emoji:"🧀",cal:350,prot:25,carb:2,fat:27,cat:"kahvalti"},
{name:"Tulum Peyniri (100g)",emoji:"🧀",cal:330,prot:22,carb:1,fat:26,cat:"kahvalti"},
{name:"Lor Peyniri (100g)",emoji:"🧀",cal:98,prot:11,carb:4,fat:4,cat:"kahvalti"},
{name:"Çökelek (100g)",emoji:"🧀",cal:72,prot:11,carb:2,fat:2,cat:"kahvalti"},
{name:"Hellim Peyniri (100g)",emoji:"🧀",cal:321,prot:25,carb:2,fat:24,cat:"kahvalti"},
{name:"Van Otlu Peynir (100g)",emoji:"🧀",cal:290,prot:20,carb:1,fat:23,cat:"kahvalti"},
{name:"Ezine Peyniri (100g)",emoji:"🧀",cal:270,prot:18,carb:1,fat:22,cat:"kahvalti"},
{name:"Mihaliç Peyniri (100g)",emoji:"🧀",cal:345,prot:24,carb:1,fat:27,cat:"kahvalti"},
{name:"Çeçil Peyniri (100g)",emoji:"🧀",cal:340,prot:28,carb:2,fat:25,cat:"kahvalti"},
{name:"Dil Peyniri (100g)",emoji:"🧀",cal:310,prot:22,carb:1,fat:24,cat:"kahvalti"},
{name:"Keçi Peyniri (100g)",emoji:"🧀",cal:364,prot:22,carb:3,fat:30,cat:"kahvalti"},
{name:"Ekmek (1 dilim)",emoji:"🍞",cal:79,prot:3,carb:15,fat:1,cat:"kahvalti"},
{name:"Tam Buğday Ekmeği (1 dilim)",emoji:"🍞",cal:69,prot:4,carb:12,fat:1,cat:"kahvalti"},
{name:"Çavdar Ekmeği (1 dilim)",emoji:"🍞",cal:65,prot:3,carb:12,fat:1,cat:"kahvalti"},
{name:"Kepekli Ekmek (1 dilim)",emoji:"🍞",cal:62,prot:3,carb:11,fat:1,cat:"kahvalti"},
{name:"Bazlama (1 adet)",emoji:"🫓",cal:280,prot:8,carb:50,fat:5,cat:"kahvalti"},
{name:"Simit",emoji:"🥯",cal:280,prot:9,carb:49,fat:5,cat:"kahvalti"},
{name:"Poğaça (peynirli)",emoji:"🥐",cal:310,prot:6,carb:35,fat:16,cat:"kahvalti"},
{name:"Poğaça (zeytinli)",emoji:"🥐",cal:290,prot:5,carb:33,fat:15,cat:"kahvalti"},
{name:"Açma",emoji:"🥐",cal:290,prot:7,carb:38,fat:13,cat:"kahvalti"},
{name:"Bal (1 yemek kaşığı)",emoji:"🍯",cal:64,prot:0,carb:17,fat:0,cat:"kahvalti"},
{name:"Tahin-Pekmez (1 yk)",emoji:"🥄",cal:90,prot:2,carb:14,fat:3,cat:"kahvalti"},
{name:"Zeytin (5 adet, yeşil)",emoji:"🫒",cal:25,prot:0,carb:1,fat:2,cat:"kahvalti"},
{name:"Zeytin (5 adet, siyah)",emoji:"🫒",cal:30,prot:0,carb:1,fat:3,cat:"kahvalti"},
{name:"Domates (1 orta)",emoji:"🍅",cal:22,prot:1,carb:5,fat:0,cat:"kahvalti"},
{name:"Salatalık (1 orta)",emoji:"🥒",cal:15,prot:1,carb:3,fat:0,cat:"kahvalti"},
{name:"Sucuk (2 dilim)",emoji:"🥓",cal:120,prot:7,carb:1,fat:10,cat:"kahvalti"},
{name:"Pastırma (3 dilim)",emoji:"🥓",cal:60,prot:10,carb:0,fat:2,cat:"kahvalti"},
{name:"Kaymak (1 yk)",emoji:"🥛",cal:90,prot:1,carb:1,fat:10,cat:"kahvalti"},
{name:"Reçel (çilek, 1 yk)",emoji:"🍓",cal:50,prot:0,carb:13,fat:0,cat:"kahvalti"},
{name:"Reçel (kayısı, 1 yk)",emoji:"🟠",cal:48,prot:0,carb:12,fat:0,cat:"kahvalti"},
{name:"Reçel (vişne, 1 yk)",emoji:"🍒",cal:50,prot:0,carb:13,fat:0,cat:"kahvalti"},
{name:"Pişi (1 adet)",emoji:"🍩",cal:200,prot:4,carb:28,fat:8,cat:"kahvalti"},
{name:"Sigara Böreği (1 adet)",emoji:"🥧",cal:90,prot:3,carb:8,fat:5,cat:"kahvalti"},
{name:"Gözleme (peynirli)",emoji:"🫓",cal:250,prot:10,carb:30,fat:10,cat:"kahvalti"},
{name:"Katmer (1 adet)",emoji:"🫓",cal:350,prot:6,carb:32,fat:22,cat:"kahvalti"},

// ═══════════════════════════════════════════
// ══  ÇORBALAR (1 kase ~250ml)            ══
// ═══════════════════════════════════════════
{name:"Mercimek Çorbası",emoji:"🍲",cal:56,prot:4,carb:9,fat:1,cat:"corba"},
{name:"Ezogelin Çorbası",emoji:"🍲",cal:68,prot:3,carb:11,fat:2,cat:"corba"},
{name:"Domates Çorbası",emoji:"🍲",cal:45,prot:1,carb:8,fat:1,cat:"corba"},
{name:"Yayla Çorbası",emoji:"🍲",cal:65,prot:3,carb:7,fat:3,cat:"corba"},
{name:"Tarhana Çorbası",emoji:"🍲",cal:72,prot:3,carb:12,fat:2,cat:"corba"},
{name:"Tavuk Suyu Çorbası",emoji:"🍲",cal:35,prot:4,carb:2,fat:1,cat:"corba"},
{name:"İşkembe Çorbası",emoji:"🍲",cal:72,prot:6,carb:4,fat:4,cat:"corba"},
{name:"Düğün Çorbası",emoji:"🍲",cal:85,prot:5,carb:8,fat:4,cat:"corba"},
{name:"Sebze Çorbası",emoji:"🍲",cal:42,prot:2,carb:7,fat:1,cat:"corba"},
{name:"Mantar Çorbası",emoji:"🍄",cal:55,prot:2,carb:6,fat:3,cat:"corba"},
{name:"Şehriye Çorbası",emoji:"🍲",cal:50,prot:3,carb:8,fat:1,cat:"corba"},
{name:"Toyga Çorbası",emoji:"🍲",cal:70,prot:4,carb:8,fat:3,cat:"corba"},
{name:"Analı Kızlı Çorbası",emoji:"🍲",cal:95,prot:5,carb:12,fat:3,cat:"corba"},
{name:"Yüksük Çorbası",emoji:"🍲",cal:80,prot:4,carb:10,fat:3,cat:"corba"},
{name:"Lebeniye Çorbası",emoji:"🍲",cal:78,prot:4,carb:10,fat:3,cat:"corba"},
{name:"Ekşili Köfte Çorbası",emoji:"🍲",cal:90,prot:5,carb:11,fat:3,cat:"corba"},
{name:"Paça Çorbası",emoji:"🍲",cal:82,prot:7,carb:3,fat:5,cat:"corba"},
{name:"Kelle Paça Çorbası",emoji:"🍲",cal:90,prot:8,carb:3,fat:5,cat:"corba"},
{name:"Balık Çorbası",emoji:"🐟",cal:65,prot:6,carb:5,fat:3,cat:"corba"},
{name:"Tutmaç Çorbası",emoji:"🍲",cal:85,prot:4,carb:12,fat:3,cat:"corba"},
{name:"Arabaşı Çorbası",emoji:"🍲",cal:88,prot:5,carb:10,fat:3,cat:"corba"},
{name:"Süleymaniye Çorbası",emoji:"🍲",cal:75,prot:4,carb:9,fat:3,cat:"corba"},
{name:"Yoğurt Çorbası",emoji:"🍲",cal:62,prot:3,carb:7,fat:3,cat:"corba"},
{name:"Un Çorbası",emoji:"🍲",cal:55,prot:2,carb:9,fat:2,cat:"corba"},
{name:"Mahluta Çorbası",emoji:"🍲",cal:75,prot:4,carb:11,fat:2,cat:"corba"},
{name:"Havuç Çorbası",emoji:"🥕",cal:48,prot:1,carb:8,fat:2,cat:"corba"},
{name:"Kabak Çorbası",emoji:"🥒",cal:40,prot:1,carb:6,fat:2,cat:"corba"},
{name:"Brokoli Çorbası",emoji:"🥦",cal:50,prot:3,carb:6,fat:2,cat:"corba"},
{name:"Karnabahar Çorbası",emoji:"🥬",cal:45,prot:2,carb:6,fat:2,cat:"corba"},
{name:"Patates Çorbası",emoji:"🥔",cal:58,prot:2,carb:10,fat:1,cat:"corba"},
{name:"Kremalı Mantar Çorbası",emoji:"🍄",cal:72,prot:2,carb:7,fat:4,cat:"corba"},
{name:"Soğan Çorbası",emoji:"🧅",cal:50,prot:2,carb:8,fat:1,cat:"corba"},
{name:"Beyran Çorbası",emoji:"🍲",cal:110,prot:9,carb:6,fat:6,cat:"corba"},
{name:"Kellecoş Çorbası",emoji:"🍲",cal:95,prot:7,carb:5,fat:5,cat:"corba"},
{name:"Pırasa Çorbası",emoji:"🥬",cal:48,prot:2,carb:7,fat:2,cat:"corba"},
{name:"Kereviz Çorbası",emoji:"🥬",cal:42,prot:1,carb:7,fat:1,cat:"corba"},

// ═══════════════════════════════════════════
// ══  ET & KEBAP                           ══
// ═══════════════════════════════════════════
// — Ham Et (100g) —
{name:"Tavuk Göğsü (100g)",emoji:"🍗",cal:165,prot:31,carb:0,fat:4,cat:"et"},
{name:"Tavuk But (100g)",emoji:"🍗",cal:209,prot:26,carb:0,fat:11,cat:"et"},
{name:"Tavuk Kanat (100g)",emoji:"🍗",cal:203,prot:30,carb:0,fat:8,cat:"et"},
{name:"Dana Kıyma (100g)",emoji:"🥩",cal:250,prot:26,carb:0,fat:15,cat:"et"},
{name:"Dana Biftek (100g)",emoji:"🥩",cal:271,prot:26,carb:0,fat:18,cat:"et"},
{name:"Kuzu Eti (100g)",emoji:"🥩",cal:294,prot:25,carb:0,fat:21,cat:"et"},
{name:"Dana Bonfile (100g)",emoji:"🥩",cal:218,prot:28,carb:0,fat:11,cat:"et"},
{name:"Dana Antrikot (100g)",emoji:"🥩",cal:260,prot:27,carb:0,fat:16,cat:"et"},
{name:"Dana Kuşbaşı (100g)",emoji:"🥩",cal:230,prot:27,carb:0,fat:13,cat:"et"},
{name:"Kuzu Pirzola (100g)",emoji:"🥩",cal:282,prot:24,carb:0,fat:20,cat:"et"},
{name:"Kuzu İncik (100g)",emoji:"🥩",cal:265,prot:26,carb:0,fat:17,cat:"et"},
{name:"Kuzu Kaburga (100g)",emoji:"🥩",cal:310,prot:22,carb:0,fat:24,cat:"et"},
{name:"Dana Ciğer (100g)",emoji:"🥩",cal:135,prot:21,carb:4,fat:4,cat:"et"},
{name:"Hindi Eti (100g)",emoji:"🦃",cal:170,prot:30,carb:0,fat:5,cat:"et"},
// — Kebaplar (1 porsiyon) —
{name:"Adana Kebap (1 şiş)",emoji:"🥩",cal:280,prot:22,carb:2,fat:20,cat:"et"},
{name:"Urfa Kebap (1 şiş)",emoji:"🥩",cal:260,prot:23,carb:2,fat:18,cat:"et"},
{name:"Tavuk Şiş (1 şiş)",emoji:"🍢",cal:170,prot:28,carb:2,fat:5,cat:"et"},
{name:"Beyti Kebap (1 porsiyon)",emoji:"🥩",cal:450,prot:30,carb:25,fat:25,cat:"et"},
{name:"Ali Nazik Kebap",emoji:"🥩",cal:380,prot:28,carb:12,fat:24,cat:"et"},
{name:"Patlıcan Kebap (1 şiş)",emoji:"🍆",cal:300,prot:22,carb:8,fat:20,cat:"et"},
{name:"İskender (1 porsiyon)",emoji:"🥩",cal:520,prot:35,carb:35,fat:26,cat:"et"},
{name:"Testi Kebabı (1 porsiyon)",emoji:"🏺",cal:350,prot:25,carb:15,fat:20,cat:"et"},
{name:"Çöp Şiş (1 porsiyon)",emoji:"🍢",cal:280,prot:24,carb:5,fat:18,cat:"et"},
{name:"Ciğer Şiş (1 porsiyon)",emoji:"🍢",cal:220,prot:26,carb:5,fat:10,cat:"et"},
{name:"Kuzu Tandır (1 porsiyon)",emoji:"🥩",cal:380,prot:30,carb:5,fat:27,cat:"et"},
{name:"Tas Kebabı (1 porsiyon)",emoji:"🥩",cal:320,prot:25,carb:10,fat:20,cat:"et"},
{name:"Orman Kebabı (1 porsiyon)",emoji:"🥩",cal:340,prot:22,carb:18,fat:20,cat:"et"},
{name:"Kağıt Kebabı (1 porsiyon)",emoji:"🥩",cal:290,prot:24,carb:10,fat:17,cat:"et"},
{name:"Hünkar Beğendi (1 porsiyon)",emoji:"🥩",cal:400,prot:25,carb:20,fat:25,cat:"et"},
{name:"Sultan Kebabı (1 porsiyon)",emoji:"🥩",cal:420,prot:28,carb:22,fat:24,cat:"et"},
{name:"Fıstıklı Kebap (Antep)",emoji:"🥩",cal:350,prot:22,carb:5,fat:27,cat:"et"},
{name:"Kilis Kebabı (1 porsiyon)",emoji:"🥩",cal:310,prot:22,carb:12,fat:19,cat:"et"},
{name:"Tike Kebab (1 şiş)",emoji:"🍢",cal:240,prot:26,carb:2,fat:14,cat:"et"},
// — Et Yemekleri (1 porsiyon) —
{name:"Döner (tavuk, 100g)",emoji:"🥙",cal:190,prot:25,carb:5,fat:8,cat:"et"},
{name:"Döner (et, 100g)",emoji:"🥙",cal:220,prot:20,carb:5,fat:13,cat:"et"},
{name:"Köfte (100g)",emoji:"🥩",cal:245,prot:25,carb:5,fat:14,cat:"et"},
{name:"İzgara Köfte (1 adet)",emoji:"🥩",cal:90,prot:9,carb:2,fat:5,cat:"et"},
{name:"İnegöl Köfte (1 adet)",emoji:"🥩",cal:95,prot:9,carb:3,fat:5,cat:"et"},
{name:"Kadınbudu Köfte (1 adet)",emoji:"🥩",cal:120,prot:8,carb:8,fat:6,cat:"et"},
{name:"Çiğ Köfte (100g)",emoji:"🟤",cal:210,prot:8,carb:30,fat:7,cat:"et"},
{name:"İçli Köfte (1 adet)",emoji:"🥩",cal:160,prot:8,carb:18,fat:6,cat:"et"},
{name:"Analı Kızlı Köfte (1 porsiyon)",emoji:"🥩",cal:320,prot:18,carb:28,fat:15,cat:"et"},
{name:"Lahmacun (1 adet)",emoji:"🫓",cal:210,prot:9,carb:28,fat:7,cat:"et"},
{name:"Tantuni (1 porsiyon)",emoji:"🌯",cal:380,prot:25,carb:30,fat:18,cat:"et"},
{name:"Dana Kavurma (1 porsiyon)",emoji:"🥩",cal:320,prot:28,carb:2,fat:22,cat:"et"},
{name:"Kuzu Kavurma (1 porsiyon)",emoji:"🥩",cal:350,prot:26,carb:2,fat:27,cat:"et"},
{name:"Sac Kavurma (1 porsiyon)",emoji:"🥘",cal:340,prot:25,carb:8,fat:23,cat:"et"},
{name:"Et Sote (1 porsiyon)",emoji:"🥘",cal:280,prot:24,carb:10,fat:16,cat:"et"},
{name:"Dana Haşlama (1 porsiyon)",emoji:"🥩",cal:260,prot:28,carb:8,fat:12,cat:"et"},
{name:"Tavuk Sote (1 porsiyon)",emoji:"🍗",cal:220,prot:26,carb:8,fat:9,cat:"et"},
{name:"Tavuk Güveç (1 porsiyon)",emoji:"🍗",cal:240,prot:24,carb:12,fat:10,cat:"et"},
{name:"Fırın Tavuk (100g)",emoji:"🍗",cal:190,prot:27,carb:0,fat:9,cat:"et"},
{name:"Çerkez Tavuğu (1 porsiyon)",emoji:"🍗",cal:280,prot:20,carb:8,fat:19,cat:"et"},
{name:"Arnavut Ciğeri (1 porsiyon)",emoji:"🥩",cal:250,prot:22,carb:10,fat:14,cat:"et"},
{name:"Ciğer Kavurma (1 porsiyon)",emoji:"🥩",cal:230,prot:24,carb:5,fat:12,cat:"et"},
{name:"Sucuk Izgara (2 dilim)",emoji:"🥓",cal:160,prot:9,carb:1,fat:14,cat:"et"},
{name:"Mumbar Dolması (1 porsiyon)",emoji:"🥩",cal:280,prot:12,carb:22,fat:16,cat:"et"},
{name:"Dana Rosto (1 porsiyon)",emoji:"🥩",cal:300,prot:30,carb:5,fat:18,cat:"et"},
{name:"Kuzu Güveç (1 porsiyon)",emoji:"🥘",cal:330,prot:25,carb:14,fat:20,cat:"et"},
{name:"Etli Güveç (1 porsiyon)",emoji:"🥘",cal:310,prot:24,carb:15,fat:17,cat:"et"},

// ═══════════════════════════════════════════
// ══  BALIK & DENİZ ÜRÜNLERİ              ══
// ═══════════════════════════════════════════
{name:"Hamsi (100g)",emoji:"🐟",cal:131,prot:20,carb:0,fat:5,cat:"balik"},
{name:"Hamsi Tava (100g)",emoji:"🐟",cal:210,prot:18,carb:8,fat:12,cat:"balik"},
{name:"Hamsi Buğulama (100g)",emoji:"🐟",cal:145,prot:20,carb:1,fat:7,cat:"balik"},
{name:"Levrek (100g)",emoji:"🐟",cal:97,prot:18,carb:0,fat:2,cat:"balik"},
{name:"Levrek Izgara (100g)",emoji:"🐟",cal:120,prot:22,carb:0,fat:3,cat:"balik"},
{name:"Çipura (100g)",emoji:"🐟",cal:100,prot:19,carb:0,fat:2,cat:"balik"},
{name:"Çipura Izgara (100g)",emoji:"🐟",cal:125,prot:23,carb:0,fat:3,cat:"balik"},
{name:"Somon (100g)",emoji:"🐟",cal:208,prot:20,carb:0,fat:13,cat:"balik"},
{name:"Somon Izgara (100g)",emoji:"🐟",cal:220,prot:25,carb:0,fat:13,cat:"balik"},
{name:"Palamut (100g)",emoji:"🐟",cal:158,prot:22,carb:0,fat:7,cat:"balik"},
{name:"Lüfer (100g)",emoji:"🐟",cal:124,prot:20,carb:0,fat:4,cat:"balik"},
{name:"Alabalık (100g)",emoji:"🐟",cal:119,prot:20,carb:0,fat:4,cat:"balik"},
{name:"Alabalık Izgara (100g)",emoji:"🐟",cal:140,prot:24,carb:0,fat:5,cat:"balik"},
{name:"Ton Balığı (konserve, 100g)",emoji:"🐟",cal:132,prot:29,carb:0,fat:1,cat:"balik"},
{name:"Karides (100g)",emoji:"🦐",cal:99,prot:24,carb:0,fat:0,cat:"balik"},
{name:"Midye Dolma (1 adet)",emoji:"🐚",cal:35,prot:2,carb:4,fat:1,cat:"balik"},
{name:"Midye Tava (6 adet)",emoji:"🐚",cal:210,prot:12,carb:15,fat:11,cat:"balik"},
{name:"Mezgit (100g)",emoji:"🐟",cal:82,prot:18,carb:0,fat:1,cat:"balik"},
{name:"Barbun (100g)",emoji:"🐟",cal:91,prot:19,carb:0,fat:1,cat:"balik"},
{name:"Kalkan (100g)",emoji:"🐟",cal:95,prot:16,carb:0,fat:3,cat:"balik"},
{name:"Uskumru (100g)",emoji:"🐟",cal:205,prot:19,carb:0,fat:14,cat:"balik"},
{name:"İstavrit (100g)",emoji:"🐟",cal:126,prot:21,carb:0,fat:5,cat:"balik"},
{name:"Sardalya (100g)",emoji:"🐟",cal:208,prot:25,carb:0,fat:11,cat:"balik"},
{name:"Kefal (100g)",emoji:"🐟",cal:117,prot:19,carb:0,fat:4,cat:"balik"},
{name:"Dil Balığı (100g)",emoji:"🐟",cal:86,prot:18,carb:0,fat:1,cat:"balik"},
{name:"Kalamar (100g)",emoji:"🦑",cal:92,prot:16,carb:3,fat:1,cat:"balik"},
{name:"Kalamar Tava (100g)",emoji:"🦑",cal:175,prot:15,carb:10,fat:8,cat:"balik"},
{name:"Ahtapot (100g)",emoji:"🐙",cal:82,prot:15,carb:2,fat:1,cat:"balik"},
{name:"Balık Buğulama (100g)",emoji:"🐟",cal:130,prot:20,carb:3,fat:4,cat:"balik"},
{name:"Balık Izgara (genel, 100g)",emoji:"🐟",cal:140,prot:22,carb:0,fat:5,cat:"balik"},

// ═══════════════════════════════════════════
// ══  SEBZE YEMEKLERİ                     ══
// ═══════════════════════════════════════════
// — Çiğ Sebzeler (100g) —
{name:"Salata (karışık)",emoji:"🥗",cal:20,prot:1,carb:4,fat:0,cat:"sebze"},
{name:"Ispanak (100g)",emoji:"🥬",cal:23,prot:3,carb:4,fat:0,cat:"sebze"},
{name:"Brokoli (100g)",emoji:"🥦",cal:34,prot:3,carb:7,fat:0,cat:"sebze"},
{name:"Havuç (1 orta)",emoji:"🥕",cal:41,prot:1,carb:10,fat:0,cat:"sebze"},
{name:"Biber (dolmalık, 1)",emoji:"🫑",cal:20,prot:1,carb:5,fat:0,cat:"sebze"},
{name:"Patlıcan (100g)",emoji:"🍆",cal:25,prot:1,carb:6,fat:0,cat:"sebze"},
{name:"Kabak (100g)",emoji:"🥒",cal:17,prot:1,carb:3,fat:0,cat:"sebze"},
{name:"Soğan (1 orta)",emoji:"🧅",cal:44,prot:1,carb:10,fat:0,cat:"sebze"},
{name:"Sarımsak (1 diş)",emoji:"🧄",cal:5,prot:0,carb:1,fat:0,cat:"sebze"},
{name:"Patates (100g)",emoji:"🥔",cal:77,prot:2,carb:17,fat:0,cat:"sebze"},
{name:"Tatlı Patates (100g)",emoji:"🍠",cal:86,prot:2,carb:20,fat:0,cat:"sebze"},
{name:"Bamya (100g)",emoji:"🥬",cal:33,prot:2,carb:7,fat:0,cat:"sebze"},
{name:"Enginar (1 adet)",emoji:"🌿",cal:47,prot:3,carb:11,fat:0,cat:"sebze"},
{name:"Karnabahar (100g)",emoji:"🥬",cal:25,prot:2,carb:5,fat:0,cat:"sebze"},
{name:"Lahana (100g)",emoji:"🥬",cal:25,prot:1,carb:6,fat:0,cat:"sebze"},
{name:"Marul (100g)",emoji:"🥬",cal:15,prot:1,carb:3,fat:0,cat:"sebze"},
{name:"Roka (100g)",emoji:"🥬",cal:25,prot:3,carb:4,fat:1,cat:"sebze"},
{name:"Semizotu (100g)",emoji:"🌿",cal:20,prot:2,carb:3,fat:0,cat:"sebze"},
{name:"Pırasa (100g)",emoji:"🥬",cal:61,prot:2,carb:14,fat:0,cat:"sebze"},
{name:"Kereviz (100g)",emoji:"🥬",cal:42,prot:2,carb:9,fat:0,cat:"sebze"},
{name:"Pancar (100g)",emoji:"🟣",cal:43,prot:2,carb:10,fat:0,cat:"sebze"},
{name:"Turp (100g)",emoji:"🔴",cal:16,prot:1,carb:3,fat:0,cat:"sebze"},
{name:"Bezelye (100g)",emoji:"🟢",cal:81,prot:5,carb:14,fat:0,cat:"sebze"},
{name:"Taze Fasulye (100g)",emoji:"🫛",cal:31,prot:2,carb:7,fat:0,cat:"sebze"},
{name:"Mısır (100g)",emoji:"🌽",cal:86,prot:3,carb:19,fat:1,cat:"sebze"},
// — Pişmiş Sebze Yemekleri (1 porsiyon) —
{name:"Karnıyarık (1 porsiyon)",emoji:"🍆",cal:180,prot:8,carb:12,fat:12,cat:"sebze"},
{name:"İmam Bayıldı (1 porsiyon)",emoji:"🍆",cal:120,prot:3,carb:10,fat:8,cat:"sebze"},
{name:"Patlıcan Musakka (1 porsiyon)",emoji:"🍆",cal:200,prot:10,carb:14,fat:12,cat:"sebze"},
{name:"Kabak Musakka (1 porsiyon)",emoji:"🥒",cal:170,prot:9,carb:12,fat:10,cat:"sebze"},
{name:"Patlıcan Oturtma (1 porsiyon)",emoji:"🍆",cal:190,prot:9,carb:12,fat:12,cat:"sebze"},
{name:"Zeytinyağlı Fasulye (1 porsiyon)",emoji:"🫛",cal:95,prot:3,carb:10,fat:5,cat:"sebze"},
{name:"Zeytinyağlı Pırasa (1 porsiyon)",emoji:"🥬",cal:85,prot:2,carb:12,fat:4,cat:"sebze"},
{name:"Zeytinyağlı Enginar (1 porsiyon)",emoji:"🌿",cal:110,prot:3,carb:14,fat:5,cat:"sebze"},
{name:"Zeytinyağlı Kereviz (1 porsiyon)",emoji:"🥬",cal:100,prot:2,carb:13,fat:5,cat:"sebze"},
{name:"Zeytinyağlı Bakla (1 porsiyon)",emoji:"🫛",cal:95,prot:5,carb:12,fat:4,cat:"sebze"},
{name:"Zeytinyağlı Barbunya (1 porsiyon)",emoji:"🫘",cal:115,prot:5,carb:15,fat:4,cat:"sebze"},
{name:"Taze Fasulye (etli, 1 porsiyon)",emoji:"🫛",cal:150,prot:9,carb:10,fat:8,cat:"sebze"},
{name:"Taze Fasulye (zeytinyağlı)",emoji:"🫛",cal:90,prot:3,carb:10,fat:4,cat:"sebze"},
{name:"Türlü (sebze, 1 porsiyon)",emoji:"🥘",cal:75,prot:2,carb:10,fat:3,cat:"sebze"},
{name:"Sebze Güveç (1 porsiyon)",emoji:"🥘",cal:90,prot:3,carb:12,fat:3,cat:"sebze"},
{name:"Biber Dolma (1 porsiyon)",emoji:"🫑",cal:160,prot:7,carb:18,fat:7,cat:"sebze"},
{name:"Kabak Dolma (1 porsiyon)",emoji:"🥒",cal:150,prot:7,carb:16,fat:6,cat:"sebze"},
{name:"Lahana Dolma (1 porsiyon)",emoji:"🥬",cal:170,prot:8,carb:18,fat:7,cat:"sebze"},
{name:"Domates Dolma (1 porsiyon)",emoji:"🍅",cal:155,prot:7,carb:17,fat:7,cat:"sebze"},
{name:"Yaprak Sarma (zeytinyağlı, 1 porsiyon)",emoji:"🌿",cal:120,prot:2,carb:15,fat:6,cat:"sebze"},
{name:"Yaprak Sarma (etli, 1 porsiyon)",emoji:"🌿",cal:170,prot:8,carb:16,fat:8,cat:"sebze"},
{name:"Etli Lahana Sarma (1 porsiyon)",emoji:"🥬",cal:180,prot:10,carb:16,fat:8,cat:"sebze"},
{name:"Etli Biber Dolma (1 porsiyon)",emoji:"🫑",cal:185,prot:10,carb:17,fat:9,cat:"sebze"},
{name:"Mücver (1 adet)",emoji:"🥬",cal:90,prot:3,carb:8,fat:5,cat:"sebze"},
{name:"Ispanaklı Yumurta (1 porsiyon)",emoji:"🥬",cal:140,prot:10,carb:4,fat:9,cat:"sebze"},
{name:"Bezelye (etli, 1 porsiyon)",emoji:"🟢",cal:180,prot:12,carb:14,fat:8,cat:"sebze"},
{name:"Bezelye (zeytinyağlı, 1 porsiyon)",emoji:"🟢",cal:95,prot:4,carb:12,fat:4,cat:"sebze"},
{name:"Mantar Sote (1 porsiyon)",emoji:"🍄",cal:80,prot:4,carb:5,fat:5,cat:"sebze"},
{name:"Bamya (etli, 1 porsiyon)",emoji:"🥬",cal:150,prot:10,carb:10,fat:8,cat:"sebze"},
{name:"Bamya (zeytinyağlı, 1 porsiyon)",emoji:"🥬",cal:85,prot:3,carb:10,fat:4,cat:"sebze"},
{name:"Karnabahar Kızartma (1 porsiyon)",emoji:"🥬",cal:160,prot:5,carb:12,fat:10,cat:"sebze"},
{name:"Kabak Kızartma (1 porsiyon)",emoji:"🥒",cal:130,prot:2,carb:8,fat:10,cat:"sebze"},
{name:"Patlıcan Kızartma (1 porsiyon)",emoji:"🍆",cal:150,prot:2,carb:8,fat:12,cat:"sebze"},
{name:"Patates Haşlama (100g)",emoji:"🥔",cal:87,prot:2,carb:20,fat:0,cat:"sebze"},
{name:"Patates Püresi (1 porsiyon)",emoji:"🥔",cal:120,prot:3,carb:18,fat:4,cat:"sebze"},
{name:"Mısır Haşlama (1 adet)",emoji:"🌽",cal:120,prot:4,carb:25,fat:2,cat:"sebze"},
{name:"Semizotu (zeytinyağlı, 1 porsiyon)",emoji:"🌿",cal:70,prot:2,carb:6,fat:4,cat:"sebze"},

// ═══════════════════════════════════════════
// ══  MEZELER & SALATALAR                  ══
// ═══════════════════════════════════════════
{name:"Humus (100g)",emoji:"🫘",cal:166,prot:8,carb:14,fat:10,cat:"meze"},
{name:"Babaganuş (100g)",emoji:"🍆",cal:88,prot:2,carb:6,fat:6,cat:"meze"},
{name:"Acılı Ezme (100g)",emoji:"🌶️",cal:60,prot:2,carb:8,fat:2,cat:"meze"},
{name:"Haydari (100g)",emoji:"🥒",cal:95,prot:5,carb:4,fat:7,cat:"meze"},
{name:"Atom (100g)",emoji:"🌶️",cal:70,prot:2,carb:5,fat:5,cat:"meze"},
{name:"Tarator (100g)",emoji:"🥜",cal:110,prot:3,carb:6,fat:8,cat:"meze"},
{name:"Patlıcan Salatası (közlenmiş)",emoji:"🍆",cal:70,prot:1,carb:5,fat:5,cat:"meze"},
{name:"Havuç Tarator (100g)",emoji:"🥕",cal:85,prot:2,carb:6,fat:6,cat:"meze"},
{name:"Çoban Salatası (1 porsiyon)",emoji:"🥗",cal:60,prot:2,carb:8,fat:3,cat:"meze"},
{name:"Mevsim Salata (1 porsiyon)",emoji:"🥗",cal:45,prot:2,carb:7,fat:2,cat:"meze"},
{name:"Roka Salatası (1 porsiyon)",emoji:"🥗",cal:70,prot:3,carb:5,fat:4,cat:"meze"},
{name:"Gavurdağı Salatası (1 porsiyon)",emoji:"🥗",cal:90,prot:2,carb:8,fat:6,cat:"meze"},
{name:"Kısır (1 porsiyon)",emoji:"🌾",cal:160,prot:4,carb:22,fat:6,cat:"meze"},
{name:"Bulgur Salatası (1 porsiyon)",emoji:"🌾",cal:150,prot:4,carb:20,fat:6,cat:"meze"},
{name:"Piyaz (1 porsiyon)",emoji:"🫘",cal:130,prot:6,carb:16,fat:5,cat:"meze"},
{name:"Mercimek Köftesi (1 adet)",emoji:"🟠",cal:45,prot:2,carb:7,fat:1,cat:"meze"},
{name:"Falafel (1 adet)",emoji:"🫘",cal:57,prot:3,carb:5,fat:3,cat:"meze"},
{name:"Semizotu Salatası (1 porsiyon)",emoji:"🌿",cal:55,prot:2,carb:5,fat:3,cat:"meze"},
{name:"Pancar Salatası (1 porsiyon)",emoji:"🟣",cal:75,prot:2,carb:10,fat:3,cat:"meze"},
{name:"Börülce Salatası (1 porsiyon)",emoji:"🫘",cal:110,prot:5,carb:14,fat:4,cat:"meze"},
{name:"Yoğurtlu Semizotu (1 porsiyon)",emoji:"🌿",cal:65,prot:3,carb:5,fat:4,cat:"meze"},
{name:"Yoğurtlu Havuç (1 porsiyon)",emoji:"🥕",cal:70,prot:3,carb:8,fat:3,cat:"meze"},
{name:"Yoğurtlu Kabak (1 porsiyon)",emoji:"🥒",cal:60,prot:3,carb:5,fat:3,cat:"meze"},
{name:"Yoğurtlu Ispanak (1 porsiyon)",emoji:"🥬",cal:65,prot:4,carb:5,fat:3,cat:"meze"},
{name:"Yoğurtlu Patlıcan (1 porsiyon)",emoji:"🍆",cal:80,prot:3,carb:6,fat:5,cat:"meze"},
{name:"Muhammara (100g)",emoji:"🌶️",cal:180,prot:4,carb:12,fat:13,cat:"meze"},
{name:"Şakşuka (1 porsiyon)",emoji:"🍅",cal:100,prot:3,carb:8,fat:6,cat:"meze"},
{name:"Ezme Salata (1 porsiyon)",emoji:"🍅",cal:55,prot:1,carb:6,fat:3,cat:"meze"},
{name:"Turşu (100g)",emoji:"🥒",cal:18,prot:1,carb:3,fat:0,cat:"meze"},
{name:"Cacık (1 kase)",emoji:"🥒",cal:70,prot:4,carb:6,fat:3,cat:"meze"},
{name:"Bakla Ezmesi (100g)",emoji:"🫛",cal:110,prot:6,carb:12,fat:4,cat:"meze"},
{name:"Topik (1 porsiyon)",emoji:"🫘",cal:120,prot:4,carb:14,fat:5,cat:"meze"},
{name:"Cevizli Biber (100g)",emoji:"🌶️",cal:140,prot:4,carb:10,fat:9,cat:"meze"},

// ═══════════════════════════════════════════
// ══  BAKLAGİL YEMEKLERİ                  ══
// ═══════════════════════════════════════════
{name:"Kuru Fasulye (pişmiş, 100g)",emoji:"🫘",cal:127,prot:9,carb:21,fat:1,cat:"baklagil"},
{name:"Nohut (pişmiş, 100g)",emoji:"🫘",cal:164,prot:9,carb:27,fat:3,cat:"baklagil"},
{name:"Mercimek (pişmiş, 100g)",emoji:"🟠",cal:116,prot:9,carb:20,fat:0,cat:"baklagil"},
{name:"Barbunya (pişmiş, 100g)",emoji:"🫘",cal:143,prot:9,carb:26,fat:1,cat:"baklagil"},
{name:"Börülce (pişmiş, 100g)",emoji:"🫘",cal:116,prot:8,carb:21,fat:1,cat:"baklagil"},
{name:"Etli Nohut (1 porsiyon)",emoji:"🍲",cal:250,prot:18,carb:25,fat:9,cat:"baklagil"},
{name:"Etli Kuru Fasulye (1 porsiyon)",emoji:"🍲",cal:230,prot:16,carb:24,fat:8,cat:"baklagil"},
{name:"Kuru Fasulye Pilaki (1 porsiyon)",emoji:"🫘",cal:160,prot:9,carb:24,fat:3,cat:"baklagil"},
{name:"Barbunya Pilaki (1 porsiyon)",emoji:"🫘",cal:155,prot:8,carb:22,fat:3,cat:"baklagil"},
{name:"Nohut Yemeği (zeytinyağlı)",emoji:"🫘",cal:140,prot:7,carb:20,fat:4,cat:"baklagil"},
{name:"Maş Fasulyesi (pişmiş, 100g)",emoji:"🫘",cal:105,prot:7,carb:19,fat:0,cat:"baklagil"},
{name:"Yeşil Mercimek (pişmiş, 100g)",emoji:"🫘",cal:120,prot:9,carb:20,fat:1,cat:"baklagil"},
{name:"Fasulye Salatası (1 porsiyon)",emoji:"🫘",cal:140,prot:7,carb:18,fat:5,cat:"baklagil"},

// ═══════════════════════════════════════════
// ══  PİLAV & MAKARNA                     ══
// ═══════════════════════════════════════════
{name:"Pirinç Pilavı (1 porsiyon)",emoji:"🍚",cal:130,prot:3,carb:28,fat:0,cat:"pilav"},
{name:"Bulgur Pilavı (1 porsiyon)",emoji:"🍚",cal:110,prot:4,carb:23,fat:1,cat:"pilav"},
{name:"Nohutlu Pilav (1 porsiyon)",emoji:"🍚",cal:160,prot:5,carb:30,fat:2,cat:"pilav"},
{name:"İç Pilav (1 porsiyon)",emoji:"🍚",cal:180,prot:4,carb:28,fat:6,cat:"pilav"},
{name:"Şehriyeli Pilav (1 porsiyon)",emoji:"🍚",cal:145,prot:4,carb:28,fat:2,cat:"pilav"},
{name:"Tereyağlı Pilav (1 porsiyon)",emoji:"🍚",cal:155,prot:3,carb:26,fat:4,cat:"pilav"},
{name:"Domatesli Pilav (1 porsiyon)",emoji:"🍚",cal:140,prot:3,carb:27,fat:2,cat:"pilav"},
{name:"Firik Pilavı (1 porsiyon)",emoji:"🍚",cal:135,prot:4,carb:26,fat:2,cat:"pilav"},
{name:"Düğün Pilavı (1 porsiyon)",emoji:"🍚",cal:180,prot:4,carb:28,fat:6,cat:"pilav"},
{name:"Tavuklu Pilav (1 porsiyon)",emoji:"🍚",cal:200,prot:12,carb:28,fat:4,cat:"pilav"},
{name:"Midyeli Pilav (1 porsiyon)",emoji:"🐚",cal:190,prot:8,carb:28,fat:5,cat:"pilav"},
{name:"Domatesli Bulgur Pilavı (1 porsiyon)",emoji:"🍚",cal:120,prot:4,carb:22,fat:2,cat:"pilav"},
{name:"Makarna (pişmiş, 100g)",emoji:"🍝",cal:158,prot:6,carb:31,fat:1,cat:"pilav"},
{name:"Kıymalı Makarna (1 porsiyon)",emoji:"🍝",cal:210,prot:12,carb:28,fat:6,cat:"pilav"},
{name:"Soslu Makarna (1 porsiyon)",emoji:"🍝",cal:180,prot:6,carb:30,fat:4,cat:"pilav"},
{name:"Fırın Makarna (1 porsiyon)",emoji:"🍝",cal:240,prot:10,carb:28,fat:10,cat:"pilav"},
{name:"Mantarlı Makarna (1 porsiyon)",emoji:"🍝",cal:190,prot:7,carb:28,fat:5,cat:"pilav"},
{name:"Erişte (100g)",emoji:"🍝",cal:180,prot:6,carb:34,fat:3,cat:"pilav"},
{name:"Mantı (1 porsiyon)",emoji:"🥟",cal:350,prot:15,carb:42,fat:13,cat:"pilav"},
{name:"Kıymalı Mantı (1 porsiyon)",emoji:"🥟",cal:380,prot:18,carb:42,fat:15,cat:"pilav"},
{name:"Lazanya (1 porsiyon)",emoji:"🍝",cal:280,prot:14,carb:28,fat:12,cat:"pilav"},
{name:"Makarna Salatası (1 porsiyon)",emoji:"🍝",cal:190,prot:5,carb:26,fat:7,cat:"pilav"},

// ═══════════════════════════════════════════
// ══  HAMUR İŞİ                           ══
// ═══════════════════════════════════════════
{name:"Su Böreği (1 dilim)",emoji:"🥧",cal:240,prot:8,carb:22,fat:13,cat:"hamur"},
{name:"Peynirli Börek (1 dilim)",emoji:"🥧",cal:280,prot:9,carb:25,fat:16,cat:"hamur"},
{name:"Kıymalı Börek (1 dilim)",emoji:"🥧",cal:310,prot:12,carb:25,fat:18,cat:"hamur"},
{name:"Ispanaklı Börek (1 dilim)",emoji:"🥧",cal:250,prot:8,carb:24,fat:14,cat:"hamur"},
{name:"Patatesli Börek (1 dilim)",emoji:"🥧",cal:260,prot:6,carb:28,fat:14,cat:"hamur"},
{name:"Kol Böreği (1 dilim)",emoji:"🥧",cal:270,prot:8,carb:26,fat:15,cat:"hamur"},
{name:"Sigara Böreği (1 adet)",emoji:"🥧",cal:90,prot:3,carb:8,fat:5,cat:"hamur"},
{name:"Çiğ Börek / Tatar Böreği (1 adet)",emoji:"🥧",cal:180,prot:7,carb:16,fat:10,cat:"hamur"},
{name:"Sarıyer Böreği (1 adet)",emoji:"🥧",cal:200,prot:6,carb:18,fat:12,cat:"hamur"},
{name:"Paçanga Böreği (1 adet)",emoji:"🥧",cal:150,prot:6,carb:12,fat:9,cat:"hamur"},
{name:"Tepsi Böreği (1 dilim)",emoji:"🥧",cal:260,prot:8,carb:25,fat:14,cat:"hamur"},
{name:"Gözleme (peynirli)",emoji:"🫓",cal:250,prot:10,carb:30,fat:10,cat:"hamur"},
{name:"Gözleme (kıymalı)",emoji:"🫓",cal:290,prot:14,carb:28,fat:14,cat:"hamur"},
{name:"Gözleme (patatesli)",emoji:"🫓",cal:260,prot:6,carb:34,fat:10,cat:"hamur"},
{name:"Gözleme (ıspanaklı)",emoji:"🫓",cal:240,prot:8,carb:28,fat:10,cat:"hamur"},
{name:"Pide (kıymalı, 1 dilim)",emoji:"🫓",cal:280,prot:13,carb:30,fat:12,cat:"hamur"},
{name:"Pide (kaşarlı, 1 dilim)",emoji:"🫓",cal:300,prot:12,carb:28,fat:16,cat:"hamur"},
{name:"Pide (kuşbaşılı, 1 dilim)",emoji:"🫓",cal:290,prot:15,carb:28,fat:13,cat:"hamur"},
{name:"Pide (sucuklu, 1 dilim)",emoji:"🫓",cal:320,prot:14,carb:28,fat:17,cat:"hamur"},
{name:"Pide (yumurtalı, 1 dilim)",emoji:"🫓",cal:270,prot:12,carb:28,fat:12,cat:"hamur"},
{name:"Karadeniz Pidesi (1 dilim)",emoji:"🫓",cal:260,prot:10,carb:30,fat:11,cat:"hamur"},
{name:"Etli Ekmek (Konya, 1 dilim)",emoji:"🫓",cal:250,prot:12,carb:28,fat:10,cat:"hamur"},
{name:"Bafra Pidesi (1 dilim)",emoji:"🫓",cal:240,prot:10,carb:28,fat:10,cat:"hamur"},
{name:"Katmer (Antep, 1 adet)",emoji:"🫓",cal:350,prot:6,carb:32,fat:22,cat:"hamur"},
{name:"Pişi (1 adet)",emoji:"🍩",cal:200,prot:4,carb:28,fat:8,cat:"hamur"},
{name:"Bazlama (1 adet)",emoji:"🫓",cal:280,prot:8,carb:50,fat:5,cat:"hamur"},
{name:"Lavaş (1 adet)",emoji:"🫓",cal:120,prot:4,carb:22,fat:2,cat:"hamur"},
{name:"Yufka (1 yaprak)",emoji:"🫓",cal:100,prot:3,carb:20,fat:1,cat:"hamur"},
{name:"Sac Böreği (1 dilim)",emoji:"🥧",cal:230,prot:7,carb:24,fat:12,cat:"hamur"},
{name:"Çiçek Böreği (1 dilim)",emoji:"🥧",cal:250,prot:8,carb:24,fat:14,cat:"hamur"},

// ═══════════════════════════════════════════
// ══  TATLI                                ══
// ═══════════════════════════════════════════
{name:"Baklava (1 dilim)",emoji:"🍯",cal:240,prot:4,carb:30,fat:12,cat:"tatli"},
{name:"Fıstıklı Baklava (1 dilim)",emoji:"🍯",cal:260,prot:5,carb:28,fat:14,cat:"tatli"},
{name:"Cevizli Baklava (1 dilim)",emoji:"🍯",cal:250,prot:4,carb:28,fat:14,cat:"tatli"},
{name:"Künefe (1 dilim)",emoji:"🧀",cal:320,prot:6,carb:38,fat:16,cat:"tatli"},
{name:"Kadayıf (1 dilim)",emoji:"🍯",cal:280,prot:4,carb:36,fat:14,cat:"tatli"},
{name:"Tel Kadayıf (1 dilim)",emoji:"🍯",cal:290,prot:4,carb:38,fat:14,cat:"tatli"},
{name:"Ekmek Kadayıfı (1 dilim)",emoji:"🍯",cal:250,prot:4,carb:35,fat:10,cat:"tatli"},
{name:"Sütlaç (1 kase)",emoji:"🍮",cal:160,prot:5,carb:26,fat:4,cat:"tatli"},
{name:"Fırın Sütlaç (1 kase)",emoji:"🍮",cal:180,prot:5,carb:28,fat:5,cat:"tatli"},
{name:"Kazandibi (1 kase)",emoji:"🍮",cal:180,prot:5,carb:28,fat:5,cat:"tatli"},
{name:"Tavuk Göğsü (tatlı, 1 kase)",emoji:"🍮",cal:175,prot:6,carb:27,fat:5,cat:"tatli"},
{name:"Muhallebi (1 kase)",emoji:"🍮",cal:150,prot:4,carb:25,fat:4,cat:"tatli"},
{name:"Keşkül (1 kase)",emoji:"🍮",cal:170,prot:4,carb:26,fat:5,cat:"tatli"},
{name:"Kemalpaşa (3 adet)",emoji:"🍯",cal:220,prot:4,carb:35,fat:8,cat:"tatli"},
{name:"Şekerpare (1 adet)",emoji:"🍯",cal:180,prot:3,carb:28,fat:7,cat:"tatli"},
{name:"Revani (1 dilim)",emoji:"🍰",cal:200,prot:3,carb:32,fat:7,cat:"tatli"},
{name:"Aşure (1 kase)",emoji:"🍲",cal:200,prot:4,carb:40,fat:3,cat:"tatli"},
{name:"Lokma (5 adet)",emoji:"🍩",cal:250,prot:3,carb:35,fat:11,cat:"tatli"},
{name:"Helva (un, 1 dilim)",emoji:"🟤",cal:180,prot:2,carb:22,fat:10,cat:"tatli"},
{name:"İrmik Helvası (1 dilim)",emoji:"🟤",cal:195,prot:3,carb:24,fat:10,cat:"tatli"},
{name:"Tahin Helvası (100g)",emoji:"🟤",cal:516,prot:12,carb:55,fat:28,cat:"tatli"},
{name:"Dondurma (1 top)",emoji:"🍦",cal:130,prot:2,carb:18,fat:6,cat:"tatli"},
{name:"Maraş Dondurması (1 top)",emoji:"🍦",cal:150,prot:3,carb:20,fat:6,cat:"tatli"},
{name:"Güllaç (1 yaprak)",emoji:"🥛",cal:140,prot:4,carb:22,fat:4,cat:"tatli"},
{name:"Tulumba (3 adet)",emoji:"🍯",cal:210,prot:2,carb:30,fat:9,cat:"tatli"},
{name:"Kabak Tatlısı (1 porsiyon)",emoji:"🎃",cal:160,prot:1,carb:35,fat:2,cat:"tatli"},
{name:"Ayva Tatlısı (1 porsiyon)",emoji:"🟡",cal:170,prot:1,carb:38,fat:1,cat:"tatli"},
{name:"İncir Tatlısı (1 porsiyon)",emoji:"🟤",cal:180,prot:1,carb:40,fat:2,cat:"tatli"},
{name:"Höşmerim (1 porsiyon)",emoji:"🧀",cal:250,prot:6,carb:25,fat:14,cat:"tatli"},
{name:"Zerde (1 kase)",emoji:"🟡",cal:180,prot:2,carb:38,fat:2,cat:"tatli"},
{name:"Pişmaniye (100g)",emoji:"🧵",cal:480,prot:6,carb:70,fat:20,cat:"tatli"},
{name:"Lokum (2 adet)",emoji:"🍬",cal:100,prot:0,carb:25,fat:0,cat:"tatli"},
{name:"Supangle (1 kase)",emoji:"🍫",cal:220,prot:4,carb:30,fat:10,cat:"tatli"},
{name:"Profiterol (1 porsiyon)",emoji:"🍫",cal:350,prot:6,carb:38,fat:20,cat:"tatli"},
{name:"Trileçe (1 dilim)",emoji:"🍰",cal:280,prot:5,carb:36,fat:13,cat:"tatli"},
{name:"Cennet Çamuru (1 kase)",emoji:"🍮",cal:200,prot:4,carb:32,fat:6,cat:"tatli"},
{name:"Un Kurabiyesi (3 adet)",emoji:"🍪",cal:180,prot:2,carb:24,fat:8,cat:"tatli"},
{name:"Acıbadem Kurabiyesi (3 adet)",emoji:"🍪",cal:160,prot:3,carb:18,fat:8,cat:"tatli"},
{name:"Elmalı Kurabiye (1 adet)",emoji:"🍪",cal:110,prot:1,carb:16,fat:5,cat:"tatli"},
{name:"Kalburabastı (1 adet)",emoji:"🍯",cal:200,prot:3,carb:30,fat:8,cat:"tatli"},
{name:"Dilber Dudağı (1 adet)",emoji:"🍯",cal:180,prot:2,carb:26,fat:8,cat:"tatli"},
{name:"Hanım Göbeği (1 adet)",emoji:"🍯",cal:190,prot:2,carb:28,fat:8,cat:"tatli"},
{name:"San Sebastian Cheesecake (1 dilim)",emoji:"🍰",cal:350,prot:6,carb:22,fat:26,cat:"tatli"},
{name:"Mozaik Pasta (1 dilim)",emoji:"🍫",cal:280,prot:4,carb:30,fat:16,cat:"tatli"},
{name:"Kek (1 dilim)",emoji:"🍰",cal:250,prot:4,carb:32,fat:12,cat:"tatli"},

// ═══════════════════════════════════════════
// ══  MEYVE                                ══
// ═══════════════════════════════════════════
{name:"Elma (1 orta)",emoji:"🍎",cal:52,prot:0,carb:14,fat:0,cat:"meyve"},
{name:"Muz (1 orta)",emoji:"🍌",cal:89,prot:1,carb:23,fat:0,cat:"meyve"},
{name:"Portakal (1 orta)",emoji:"🍊",cal:47,prot:1,carb:12,fat:0,cat:"meyve"},
{name:"Mandalina (1 adet)",emoji:"🍊",cal:35,prot:0,carb:9,fat:0,cat:"meyve"},
{name:"Üzüm (100g)",emoji:"🍇",cal:69,prot:1,carb:18,fat:0,cat:"meyve"},
{name:"Karpuz (200g)",emoji:"🍉",cal:60,prot:1,carb:15,fat:0,cat:"meyve"},
{name:"Kavun (200g)",emoji:"🍈",cal:68,prot:2,carb:16,fat:0,cat:"meyve"},
{name:"Çilek (100g)",emoji:"🍓",cal:32,prot:1,carb:8,fat:0,cat:"meyve"},
{name:"Kiraz (100g)",emoji:"🍒",cal:63,prot:1,carb:16,fat:0,cat:"meyve"},
{name:"Şeftali (1 orta)",emoji:"🍑",cal:39,prot:1,carb:10,fat:0,cat:"meyve"},
{name:"Kayısı (1 adet)",emoji:"🟠",cal:17,prot:0,carb:4,fat:0,cat:"meyve"},
{name:"İncir (taze, 1 adet)",emoji:"🟤",cal:37,prot:0,carb:10,fat:0,cat:"meyve"},
{name:"Nar (100g)",emoji:"🔴",cal:83,prot:2,carb:19,fat:1,cat:"meyve"},
{name:"Avokado (yarım)",emoji:"🥑",cal:120,prot:1,carb:6,fat:11,cat:"meyve"},
{name:"Hurma (1 adet)",emoji:"🟤",cal:66,prot:0,carb:18,fat:0,cat:"meyve"},
{name:"Armut (1 orta)",emoji:"🍐",cal:57,prot:0,carb:15,fat:0,cat:"meyve"},
{name:"Ayva (1 orta)",emoji:"🟡",cal:57,prot:0,carb:15,fat:0,cat:"meyve"},
{name:"Erik (3 adet)",emoji:"🟣",cal:46,prot:1,carb:11,fat:0,cat:"meyve"},
{name:"Vişne (100g)",emoji:"🍒",cal:50,prot:1,carb:12,fat:0,cat:"meyve"},
{name:"Böğürtlen (100g)",emoji:"🫐",cal:43,prot:1,carb:10,fat:0,cat:"meyve"},
{name:"Ahududu (100g)",emoji:"🔴",cal:52,prot:1,carb:12,fat:1,cat:"meyve"},
{name:"Dut (100g)",emoji:"🫐",cal:43,prot:1,carb:10,fat:0,cat:"meyve"},
{name:"Greyfurt (yarım)",emoji:"🍊",cal:42,prot:1,carb:11,fat:0,cat:"meyve"},
{name:"Limon (1 adet)",emoji:"🍋",cal:17,prot:1,carb:5,fat:0,cat:"meyve"},
{name:"Kivi (1 adet)",emoji:"🥝",cal:42,prot:1,carb:10,fat:0,cat:"meyve"},
{name:"Ananas (100g)",emoji:"🍍",cal:50,prot:1,carb:13,fat:0,cat:"meyve"},
{name:"Mango (100g)",emoji:"🥭",cal:60,prot:1,carb:15,fat:0,cat:"meyve"},
{name:"Trabzon Hurması (1 adet)",emoji:"🟠",cal:70,prot:1,carb:19,fat:0,cat:"meyve"},

// ═══════════════════════════════════════════
// ══  KURUYEMİŞ & KURU MEYVE              ══
// ═══════════════════════════════════════════
{name:"Badem (30g, ~23 adet)",emoji:"🥜",cal:173,prot:6,carb:6,fat:15,cat:"kuruyemis"},
{name:"Ceviz (30g, ~7 yarım)",emoji:"🥜",cal:196,prot:5,carb:4,fat:20,cat:"kuruyemis"},
{name:"Fındık (30g)",emoji:"🥜",cal:189,prot:4,carb:5,fat:18,cat:"kuruyemis"},
{name:"Antep Fıstığı (30g)",emoji:"🥜",cal:168,prot:6,carb:8,fat:13,cat:"kuruyemis"},
{name:"Yer Fıstığı (30g)",emoji:"🥜",cal:170,prot:7,carb:5,fat:14,cat:"kuruyemis"},
{name:"Kaju (30g)",emoji:"🥜",cal:166,prot:5,carb:9,fat:13,cat:"kuruyemis"},
{name:"Çam Fıstığı (30g)",emoji:"🥜",cal:202,prot:4,carb:4,fat:20,cat:"kuruyemis"},
{name:"Leblebi (30g)",emoji:"🟡",cal:120,prot:6,carb:18,fat:2,cat:"kuruyemis"},
{name:"Ay Çekirdeği (30g)",emoji:"🌻",cal:175,prot:6,carb:6,fat:15,cat:"kuruyemis"},
{name:"Kabak Çekirdeği (30g)",emoji:"🎃",cal:170,prot:9,carb:2,fat:14,cat:"kuruyemis"},
{name:"Kestane (100g)",emoji:"🌰",cal:213,prot:3,carb:45,fat:2,cat:"kuruyemis"},
{name:"Kuru Üzüm (30g)",emoji:"🍇",cal:90,prot:1,carb:24,fat:0,cat:"kuruyemis"},
{name:"Kuru Kayısı (3 adet)",emoji:"🟠",cal:60,prot:1,carb:15,fat:0,cat:"kuruyemis"},
{name:"Kuru İncir (2 adet)",emoji:"🟤",cal:94,prot:1,carb:24,fat:0,cat:"kuruyemis"},
{name:"Kuru Dut (30g)",emoji:"🫐",cal:90,prot:2,carb:20,fat:0,cat:"kuruyemis"},
{name:"Kuru Erik (3 adet)",emoji:"🟣",cal:65,prot:1,carb:17,fat:0,cat:"kuruyemis"},
{name:"Pestil (1 adet)",emoji:"🟤",cal:80,prot:1,carb:18,fat:0,cat:"kuruyemis"},
{name:"Kuru Elma (30g)",emoji:"🍎",cal:70,prot:0,carb:18,fat:0,cat:"kuruyemis"},
{name:"Mix Kuruyemiş (30g)",emoji:"🥜",cal:180,prot:5,carb:8,fat:15,cat:"kuruyemis"},

// ═══════════════════════════════════════════
// ══  SÜT ÜRÜNLERİ                        ══
// ═══════════════════════════════════════════
{name:"Süt (tam yağlı, 200ml)",emoji:"🥛",cal:120,prot:6,carb:10,fat:6,cat:"sut"},
{name:"Süt (yarım yağlı, 200ml)",emoji:"🥛",cal:92,prot:6,carb:10,fat:3,cat:"sut"},
{name:"Süt (yağsız, 200ml)",emoji:"🥛",cal:70,prot:7,carb:10,fat:0,cat:"sut"},
{name:"Laktozsuz Süt (200ml)",emoji:"🥛",cal:90,prot:6,carb:10,fat:3,cat:"sut"},
{name:"Keçi Sütü (200ml)",emoji:"🥛",cal:134,prot:7,carb:9,fat:8,cat:"sut"},
{name:"Yoğurt (200g)",emoji:"🥣",cal:122,prot:10,carb:8,fat:5,cat:"sut"},
{name:"Süzme Yoğurt (200g)",emoji:"🥣",cal:160,prot:14,carb:8,fat:8,cat:"sut"},
{name:"Yoğurt (yağsız, 200g)",emoji:"🥣",cal:80,prot:10,carb:8,fat:0,cat:"sut"},
{name:"Ayran (1 bardak)",emoji:"🥛",cal:72,prot:4,carb:6,fat:4,cat:"sut"},
{name:"Kefir (200ml)",emoji:"🥛",cal:100,prot:6,carb:8,fat:4,cat:"sut"},
{name:"Cacık (1 kase)",emoji:"🥒",cal:70,prot:4,carb:6,fat:3,cat:"sut"},
{name:"Labne (1 yk)",emoji:"🧀",cal:50,prot:2,carb:1,fat:4,cat:"sut"},
{name:"Krema (1 yk)",emoji:"🥛",cal:52,prot:0,carb:1,fat:6,cat:"sut"},
{name:"Kaymak (100g)",emoji:"🥛",cal:290,prot:2,carb:2,fat:30,cat:"sut"},
{name:"Badem Sütü (200ml)",emoji:"🥛",cal:30,prot:1,carb:1,fat:2,cat:"sut"},
{name:"Yulaf Sütü (200ml)",emoji:"🥛",cal:80,prot:1,carb:14,fat:2,cat:"sut"},
{name:"Hindistan Cevizi Sütü (200ml)",emoji:"🥛",cal:180,prot:2,carb:3,fat:18,cat:"sut"},
{name:"Taze Kaşar (100g)",emoji:"🧀",cal:313,prot:22,carb:2,fat:24,cat:"sut"},
{name:"Eski Kaşar (100g)",emoji:"🧀",cal:392,prot:28,carb:2,fat:30,cat:"sut"},

// ═══════════════════════════════════════════
// ══  İÇECEKLER                            ══
// ═══════════════════════════════════════════
{name:"Çay (şekersiz)",emoji:"🍵",cal:2,prot:0,carb:0,fat:0,cat:"icecek"},
{name:"Çay (1 şekerli)",emoji:"🍵",cal:22,prot:0,carb:5,fat:0,cat:"icecek"},
{name:"Türk Kahvesi (şekersiz)",emoji:"☕",cal:5,prot:0,carb:1,fat:0,cat:"icecek"},
{name:"Türk Kahvesi (orta)",emoji:"☕",cal:25,prot:0,carb:6,fat:0,cat:"icecek"},
{name:"Filtre Kahve (sade)",emoji:"☕",cal:5,prot:0,carb:0,fat:0,cat:"icecek"},
{name:"Nescafe (sütlü)",emoji:"☕",cal:70,prot:2,carb:8,fat:3,cat:"icecek"},
{name:"Latte",emoji:"☕",cal:150,prot:8,carb:12,fat:8,cat:"icecek"},
{name:"Cappuccino",emoji:"☕",cal:120,prot:6,carb:10,fat:6,cat:"icecek"},
{name:"Americano",emoji:"☕",cal:10,prot:0,carb:1,fat:0,cat:"icecek"},
{name:"Mocha",emoji:"☕",cal:230,prot:8,carb:28,fat:10,cat:"icecek"},
{name:"Espresso (1 shot)",emoji:"☕",cal:5,prot:0,carb:1,fat:0,cat:"icecek"},
{name:"Yeşil Çay",emoji:"🍵",cal:2,prot:0,carb:0,fat:0,cat:"icecek"},
{name:"Ihlamur (şekersiz)",emoji:"🍵",cal:5,prot:0,carb:1,fat:0,cat:"icecek"},
{name:"Bitki Çayı",emoji:"🍵",cal:2,prot:0,carb:0,fat:0,cat:"icecek"},
{name:"Elma Çayı (şekersiz)",emoji:"🍵",cal:5,prot:0,carb:1,fat:0,cat:"icecek"},
{name:"Limonata (1 bardak)",emoji:"🍋",cal:100,prot:0,carb:26,fat:0,cat:"icecek"},
{name:"Portakal Suyu (1 bardak)",emoji:"🍊",cal:112,prot:2,carb:26,fat:0,cat:"icecek"},
{name:"Vişne Suyu (1 bardak)",emoji:"🍒",cal:110,prot:0,carb:28,fat:0,cat:"icecek"},
{name:"Şeftali Suyu (1 bardak)",emoji:"🍑",cal:105,prot:0,carb:26,fat:0,cat:"icecek"},
{name:"Kayısı Suyu (1 bardak)",emoji:"🟠",cal:108,prot:1,carb:27,fat:0,cat:"icecek"},
{name:"Şalgam Suyu (1 bardak)",emoji:"🥤",cal:20,prot:1,carb:4,fat:0,cat:"icecek"},
{name:"Kola (330ml)",emoji:"🥤",cal:139,prot:0,carb:35,fat:0,cat:"icecek"},
{name:"Kola Zero (330ml)",emoji:"🥤",cal:0,prot:0,carb:0,fat:0,cat:"icecek"},
{name:"Soda",emoji:"🥤",cal:0,prot:0,carb:0,fat:0,cat:"icecek"},
{name:"Maden Suyu",emoji:"🥤",cal:0,prot:0,carb:0,fat:0,cat:"icecek"},
{name:"Gazoz (330ml)",emoji:"🥤",cal:130,prot:0,carb:33,fat:0,cat:"icecek"},
{name:"Enerji İçeceği (250ml)",emoji:"⚡",cal:112,prot:0,carb:28,fat:0,cat:"icecek"},
{name:"Boza (1 bardak)",emoji:"🥤",cal:200,prot:3,carb:40,fat:2,cat:"icecek"},
{name:"Sahlep (1 fincan)",emoji:"☕",cal:120,prot:4,carb:18,fat:4,cat:"icecek"},
{name:"Smoothie (meyve, 300ml)",emoji:"🥤",cal:160,prot:2,carb:36,fat:1,cat:"icecek"},
{name:"Protein Shake (300ml)",emoji:"🥤",cal:180,prot:25,carb:12,fat:3,cat:"icecek"},

// ═══════════════════════════════════════════
// ══  FAST FOOD & SOKAK LEZZETLERİ        ══
// ═══════════════════════════════════════════
{name:"Hamburger (klasik)",emoji:"🍔",cal:450,prot:22,carb:40,fat:22,cat:"fastfood"},
{name:"Cheeseburger",emoji:"🍔",cal:530,prot:28,carb:42,fat:28,cat:"fastfood"},
{name:"Islak Hamburger",emoji:"🍔",cal:280,prot:12,carb:28,fat:14,cat:"fastfood"},
{name:"Pizza (1 dilim)",emoji:"🍕",cal:270,prot:11,carb:33,fat:10,cat:"fastfood"},
{name:"Patates Kızartması (orta)",emoji:"🍟",cal:340,prot:4,carb:44,fat:16,cat:"fastfood"},
{name:"Tavuk Nugget (6 adet)",emoji:"🍗",cal:280,prot:14,carb:18,fat:17,cat:"fastfood"},
{name:"Çıtır Tavuk (3 parça)",emoji:"🍗",cal:350,prot:20,carb:22,fat:20,cat:"fastfood"},
{name:"Dürüm (tavuk döner)",emoji:"🌯",cal:380,prot:22,carb:35,fat:16,cat:"fastfood"},
{name:"Dürüm (et döner)",emoji:"🌯",cal:420,prot:24,carb:35,fat:20,cat:"fastfood"},
{name:"Adana Dürüm",emoji:"🌯",cal:400,prot:22,carb:32,fat:20,cat:"fastfood"},
{name:"Çiğ Köfte Dürüm",emoji:"🌯",cal:250,prot:8,carb:38,fat:7,cat:"fastfood"},
{name:"Tost (kaşarlı)",emoji:"🥪",cal:280,prot:12,carb:28,fat:14,cat:"fastfood"},
{name:"Tost (karışık)",emoji:"🥪",cal:340,prot:16,carb:28,fat:18,cat:"fastfood"},
{name:"Tombik Tost",emoji:"🥪",cal:380,prot:18,carb:32,fat:20,cat:"fastfood"},
{name:"Kumru",emoji:"🥪",cal:350,prot:16,carb:30,fat:18,cat:"fastfood"},
{name:"Kokoreç (yarım)",emoji:"🥙",cal:310,prot:18,carb:22,fat:16,cat:"fastfood"},
{name:"Kumpir (1 porsiyon)",emoji:"🥔",cal:450,prot:12,carb:55,fat:20,cat:"fastfood"},
{name:"Balık Ekmek",emoji:"🐟",cal:350,prot:20,carb:35,fat:14,cat:"fastfood"},
{name:"Waffle (1 adet)",emoji:"🧇",cal:350,prot:6,carb:42,fat:18,cat:"fastfood"},
{name:"Sosisli Sandviç",emoji:"🌭",cal:280,prot:10,carb:30,fat:13,cat:"fastfood"},
{name:"Patso",emoji:"🥔",cal:380,prot:10,carb:42,fat:18,cat:"fastfood"},
{name:"Wrap (tavuk)",emoji:"🌯",cal:320,prot:18,carb:30,fat:14,cat:"fastfood"},

// ═══════════════════════════════════════════
// ══  ATIŞTIRMALIK                         ══
// ═══════════════════════════════════════════
{name:"Çikolata (sütlü, 30g)",emoji:"🍫",cal:160,prot:2,carb:17,fat:9,cat:"atistirmalik"},
{name:"Çikolata (bitter, 30g)",emoji:"🍫",cal:155,prot:2,carb:14,fat:10,cat:"atistirmalik"},
{name:"Çikolata (beyaz, 30g)",emoji:"🍫",cal:165,prot:2,carb:17,fat:10,cat:"atistirmalik"},
{name:"Bisküvi (3 adet)",emoji:"🍪",cal:140,prot:2,carb:20,fat:6,cat:"atistirmalik"},
{name:"Kraker (5 adet)",emoji:"🍘",cal:80,prot:2,carb:13,fat:2,cat:"atistirmalik"},
{name:"Çubuk Kraker (30g)",emoji:"🥨",cal:120,prot:3,carb:20,fat:3,cat:"atistirmalik"},
{name:"Cips (30g)",emoji:"🥔",cal:160,prot:2,carb:15,fat:10,cat:"atistirmalik"},
{name:"Pirinç Patlağı (30g)",emoji:"🍚",cal:115,prot:2,carb:24,fat:1,cat:"atistirmalik"},
{name:"Granola Bar",emoji:"🥜",cal:190,prot:4,carb:28,fat:7,cat:"atistirmalik"},
{name:"Gofret (1 adet)",emoji:"🍫",cal:130,prot:1,carb:16,fat:7,cat:"atistirmalik"},
{name:"Mısır Gevreği (30g)",emoji:"🥣",cal:112,prot:2,carb:25,fat:0,cat:"atistirmalik"},
{name:"Popcorn (30g, yağsız)",emoji:"🍿",cal:108,prot:3,carb:22,fat:1,cat:"atistirmalik"},
{name:"Popcorn (30g, tereyağlı)",emoji:"🍿",cal:140,prot:2,carb:18,fat:7,cat:"atistirmalik"},
{name:"Brownie (1 adet)",emoji:"🍫",cal:250,prot:3,carb:30,fat:13,cat:"atistirmalik"},
{name:"Muffin (1 adet)",emoji:"🧁",cal:280,prot:4,carb:36,fat:13,cat:"atistirmalik"},
{name:"Kuru Pasta (3 adet)",emoji:"🍪",cal:150,prot:2,carb:20,fat:7,cat:"atistirmalik"},
{name:"Protein Ball (1 adet)",emoji:"💪",cal:80,prot:4,carb:8,fat:4,cat:"atistirmalik"},
{name:"Hurma Topları (2 adet)",emoji:"🟤",cal:120,prot:2,carb:22,fat:4,cat:"atistirmalik"},

// ═══════════════════════════════════════════
// ══  SOS & ÇEŞNİ                         ══
// ═══════════════════════════════════════════
{name:"Ketçap (1 yk)",emoji:"🍅",cal:20,prot:0,carb:5,fat:0,cat:"sos"},
{name:"Mayonez (1 yk)",emoji:"🥄",cal:94,prot:0,carb:0,fat:10,cat:"sos"},
{name:"Hardal (1 çk)",emoji:"🟡",cal:5,prot:0,carb:0,fat:0,cat:"sos"},
{name:"Salça (domates, 1 yk)",emoji:"🍅",cal:15,prot:1,carb:3,fat:0,cat:"sos"},
{name:"Salça (biber, 1 yk)",emoji:"🌶️",cal:14,prot:1,carb:3,fat:0,cat:"sos"},
{name:"Nar Ekşisi (1 yk)",emoji:"🔴",cal:30,prot:0,carb:7,fat:0,cat:"sos"},
{name:"Sumak (1 çk)",emoji:"🔴",cal:5,prot:0,carb:1,fat:0,cat:"sos"},
{name:"Pul Biber (1 çk)",emoji:"🌶️",cal:6,prot:0,carb:1,fat:0,cat:"sos"},
{name:"Karabiber (1 çk)",emoji:"⚫",cal:5,prot:0,carb:1,fat:0,cat:"sos"},
{name:"Kimyon (1 çk)",emoji:"🟤",cal:8,prot:0,carb:1,fat:0,cat:"sos"},
{name:"Zerdeçal (1 çk)",emoji:"🟡",cal:8,prot:0,carb:1,fat:0,cat:"sos"},
{name:"Kekik (1 çk)",emoji:"🌿",cal:5,prot:0,carb:1,fat:0,cat:"sos"},
{name:"Nane (kuru, 1 çk)",emoji:"🌿",cal:5,prot:0,carb:1,fat:0,cat:"sos"},
{name:"Tarçın (1 çk)",emoji:"🟤",cal:6,prot:0,carb:2,fat:0,cat:"sos"},
{name:"Soya Sosu (1 yk)",emoji:"🥄",cal:9,prot:1,carb:1,fat:0,cat:"sos"},
{name:"Acı Sos (1 çk)",emoji:"🌶️",cal:3,prot:0,carb:1,fat:0,cat:"sos"},
{name:"BBQ Sos (1 yk)",emoji:"🥄",cal:30,prot:0,carb:7,fat:0,cat:"sos"},
{name:"Ranch Sos (1 yk)",emoji:"🥄",cal:73,prot:0,carb:1,fat:8,cat:"sos"},
{name:"Tarator Sos (1 yk)",emoji:"🥄",cal:40,prot:1,carb:2,fat:3,cat:"sos"},
{name:"Ezme (acılı, 1 yk)",emoji:"🌶️",cal:15,prot:0,carb:2,fat:1,cat:"sos"},

// ═══════════════════════════════════════════
// ══  SPORCU & SAĞLIK                      ══
// ═══════════════════════════════════════════
{name:"Protein Tozu (1 ölçek, whey)",emoji:"💪",cal:120,prot:24,carb:3,fat:1,cat:"sporcu"},
{name:"Protein Tozu (kazein, 1 ölçek)",emoji:"💪",cal:120,prot:24,carb:4,fat:1,cat:"sporcu"},
{name:"Vegan Protein Tozu (1 ölçek)",emoji:"🌱",cal:110,prot:20,carb:5,fat:2,cat:"sporcu"},
{name:"BCAA (1 servis)",emoji:"💊",cal:5,prot:0,carb:1,fat:0,cat:"sporcu"},
{name:"Kreatin (5g)",emoji:"💊",cal:0,prot:0,carb:0,fat:0,cat:"sporcu"},
{name:"Yulaf Ezmesi (100g)",emoji:"🥣",cal:389,prot:17,carb:66,fat:7,cat:"sporcu"},
{name:"Chia Tohumu (1 yk)",emoji:"🌱",cal:58,prot:2,carb:5,fat:4,cat:"sporcu"},
{name:"Keten Tohumu (1 yk)",emoji:"🌱",cal:55,prot:2,carb:3,fat:4,cat:"sporcu"},
{name:"Fıstık Ezmesi (1 yk)",emoji:"🥜",cal:94,prot:4,carb:3,fat:8,cat:"sporcu"},
{name:"Badem Ezmesi (1 yk)",emoji:"🥜",cal:98,prot:3,carb:3,fat:9,cat:"sporcu"},
{name:"Protein Bar",emoji:"💪",cal:200,prot:20,carb:22,fat:6,cat:"sporcu"},
{name:"Hindistan Cevizi Yağı (1 yk)",emoji:"🥥",cal:120,prot:0,carb:0,fat:14,cat:"sporcu"},
{name:"Protein Shake (hazır)",emoji:"🥤",cal:160,prot:30,carb:6,fat:2,cat:"sporcu"},
{name:"L-Karnitin (1 servis)",emoji:"💊",cal:0,prot:0,carb:0,fat:0,cat:"sporcu"},
{name:"Glutamin (5g)",emoji:"💊",cal:20,prot:5,carb:0,fat:0,cat:"sporcu"},
{name:"Mass Gainer (1 ölçek)",emoji:"💪",cal:380,prot:20,carb:60,fat:6,cat:"sporcu"},
{name:"Pre-Workout (1 servis)",emoji:"⚡",cal:10,prot:0,carb:2,fat:0,cat:"sporcu"},
{name:"Omega-3 (1 kapsül)",emoji:"💊",cal:10,prot:0,carb:0,fat:1,cat:"sporcu"},
{name:"Keçiboynuzu Pekmezi (1 yk)",emoji:"🟤",cal:50,prot:0,carb:13,fat:0,cat:"sporcu"},
{name:"Arı Poleni (1 çk)",emoji:"🐝",cal:16,prot:1,carb:3,fat:0,cat:"sporcu"}
];
